# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cce3e10935f65370ad376c33253280d5552760f282605e78569ad3922fd564eaa8ec81595ca8ee537cd245f7572e01845920c95c3963b7a57a9a35a355156eb5

test:
  secret_key_base: b686452c95d864e8b503900ebbcc751270f2ddc65318dd69f153b9f42608deb17dce93dfd12626d9b41b35f3a8bfe113105491372a482e6f137b4f8692d6c5d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
